/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODIGOS;

import static CODIGOS.Arquivo.palavras_separadas_linha_1;
import static CODIGOS.Arquivo.palavras_separadas_linha_2;
import static CODIGOS.Arquivo.palavras_separadas_linha_3;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ibyte
 */
public class Tela extends javax.swing.JFrame {
    
    public int vez;
    public int total_de_atendimentos;
    public int atendimentos_tecnico_1;
    public int atendimentos_tecnico_2;
    public int atendimentos_tecnico_3;
    public static Color cor_do_selecionado = Color.YELLOW;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TEXTO_NOME_DA_VEZ = new javax.swing.JLabel();
        BOTAO_ZERAR = new javax.swing.JButton();
        TEXTO_TOTAL = new javax.swing.JLabel();
        TECNICO_1_BOTAO = new javax.swing.JToggleButton();
        TECNICO_2_BOTAO = new javax.swing.JToggleButton();
        TECNICO_3_BOTAO = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TEXTO_NOME_DA_VEZ.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        TEXTO_NOME_DA_VEZ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BOTAO_ZERAR.setText("ZERAR");
        BOTAO_ZERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_ZERARActionPerformed(evt);
            }
        });

        TEXTO_TOTAL.setText("ATENDIMENTOS : ");

        TECNICO_1_BOTAO.setText("TECNICO 1");
        TECNICO_1_BOTAO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TECNICO_1_BOTAOMouseClicked(evt);
            }
        });

        TECNICO_2_BOTAO.setText("TECNICO 2");
        TECNICO_2_BOTAO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TECNICO_2_BOTAOMouseClicked(evt);
            }
        });

        TECNICO_3_BOTAO.setText("TECNICO 3");
        TECNICO_3_BOTAO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TECNICO_3_BOTAOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TEXTO_NOME_DA_VEZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(TECNICO_1_BOTAO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TECNICO_2_BOTAO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TECNICO_3_BOTAO)
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(BOTAO_ZERAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEXTO_TOTAL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTAO_ZERAR)
                    .addComponent(TEXTO_TOTAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(TEXTO_NOME_DA_VEZ, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TECNICO_1_BOTAO)
                    .addComponent(TECNICO_2_BOTAO)
                    .addComponent(TECNICO_3_BOTAO))
                .addGap(66, 66, 66))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Boolean habilitar = false;
        
        CODIGOS.Pasta.criar("GaF02");//Cria a pasta principal do programa
        CODIGOS.Arquivo.criar("Tecnicos");//Cria o arquivo principal do programa
        CODIGOS.Arquivo.criar("Registros");
        CODIGOS.Arquivo.ler("Tecnicos");//Faz a leitura do arquivo principal
        
        BOTAO_ZERAR.setEnabled(habilitar);
        
        TEXTO_NOME_DA_VEZ.setForeground(Color.BLACK);
        
        TECNICO_1_BOTAO.setSelected(habilitar);
        TECNICO_1_BOTAO.setBackground(Color.green);
        TECNICO_1_BOTAO.setText(""+palavras_separadas_linha_1[0]);
        
        TECNICO_2_BOTAO.setSelected(habilitar);
        TECNICO_2_BOTAO.setBackground(Color.green);
        TECNICO_2_BOTAO.setText(""+palavras_separadas_linha_2[0]);
        
        TECNICO_3_BOTAO.setSelected(habilitar);
        TECNICO_3_BOTAO.setBackground(Color.green);
        TECNICO_3_BOTAO.setText(""+palavras_separadas_linha_3[0]);
        
    }//GEN-LAST:event_formWindowOpened

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        BOTAO_ZERAR.setEnabled(true);
        
        vez++;
        
        
        if(vez == 1 && TECNICO_1_BOTAO.isSelected()){
            vez++;
        }
        if(vez == 2 && TECNICO_2_BOTAO.isSelected()){
            vez++;
        }
        if(vez == 3 && TECNICO_3_BOTAO.isSelected()){
            vez=1;
        }
        if(TECNICO_1_BOTAO.isSelected() && TECNICO_3_BOTAO.isSelected()){
            vez=2;
        }
        
        
        if(vez == 1 && !TECNICO_1_BOTAO.isSelected()){
            
            TEXTO_NOME_DA_VEZ.setText(palavras_separadas_linha_1[0]+" - "+palavras_separadas_linha_1[1]);
            atendimentos_tecnico_1++;
            TECNICO_1_BOTAO.setText(palavras_separadas_linha_1[0]+" - "+atendimentos_tecnico_1);
            total_de_atendimentos++;
            
        }
        if(vez == 2 && !TECNICO_2_BOTAO.isSelected()){
            
            TEXTO_NOME_DA_VEZ.setText(palavras_separadas_linha_2[0]+" - "+palavras_separadas_linha_2[1]);
            atendimentos_tecnico_2++;
            TECNICO_2_BOTAO.setText(palavras_separadas_linha_2[0]+" - "+atendimentos_tecnico_2);
            total_de_atendimentos++;
            
        }
        if(vez == 3 && !TECNICO_3_BOTAO.isSelected()){ 
            
            TEXTO_NOME_DA_VEZ.setText(palavras_separadas_linha_3[0]+" - "+palavras_separadas_linha_3[1]);
            atendimentos_tecnico_3++;
            TECNICO_3_BOTAO.setText(palavras_separadas_linha_3[0]+" - "+atendimentos_tecnico_3);
            total_de_atendimentos++;
            
            vez = 0;
        }
        if(vez == 3 && TECNICO_3_BOTAO.isSelected()){
            vez = 0;
        }
        
        TEXTO_TOTAL.setText("ATENDIMENTOS : "+total_de_atendimentos);
        
        CODIGOS.Arquivo.gravar("Total de atendimentos: "+total_de_atendimentos,
                               palavras_separadas_linha_1[0]+" = "+atendimentos_tecnico_1,
                               palavras_separadas_linha_2[0]+" = "+atendimentos_tecnico_2,
                               palavras_separadas_linha_3[0]+" = "+atendimentos_tecnico_3);
        
    }//GEN-LAST:event_formMouseClicked

    private void BOTAO_ZERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_ZERARActionPerformed
        // TODO add your handling code here:
        
        Object[] options = { "Sim", "Não" };   
        int opcao = JOptionPane.showOptionDialog(null,"Deseja zerar a contagem ?","Aviso",
        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);   
  
        if (opcao != 0){
        //JOptionPane.showMessageDialog(null,"";
        }else{
        vez = 0;
        total_de_atendimentos = 0;
        atendimentos_tecnico_1 = 0;
        atendimentos_tecnico_2 = 0;
        atendimentos_tecnico_3 = 0;
        TEXTO_TOTAL.setText("ATENDIMENTOS : ");
        TEXTO_NOME_DA_VEZ.setText("");
        TECNICO_1_BOTAO.setText(""+palavras_separadas_linha_1[0]);
        TECNICO_2_BOTAO.setText(""+palavras_separadas_linha_2[0]);
        TECNICO_3_BOTAO.setText(""+palavras_separadas_linha_3[0]);
        BOTAO_ZERAR.setEnabled(false);
        } 
        
    }//GEN-LAST:event_BOTAO_ZERARActionPerformed

    private void TECNICO_1_BOTAOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TECNICO_1_BOTAOMouseClicked
        // TODO add your handling code here:
        if(TECNICO_1_BOTAO.isSelected()){
            TECNICO_1_BOTAO.setSelected(true);
            TECNICO_1_BOTAO.setBackground(Color.red);
        }else{
            TECNICO_1_BOTAO.setSelected(false);
            TECNICO_1_BOTAO.setBackground(Color.green);
        }  
    }//GEN-LAST:event_TECNICO_1_BOTAOMouseClicked

    private void TECNICO_2_BOTAOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TECNICO_2_BOTAOMouseClicked
        // TODO add your handling code here:
        if(TECNICO_2_BOTAO.isSelected()){
            TECNICO_2_BOTAO.setSelected(true);
            TECNICO_2_BOTAO.setBackground(Color.red);
        }else{
            TECNICO_2_BOTAO.setSelected(false);
            TECNICO_2_BOTAO.setBackground(Color.green);
        }
    }//GEN-LAST:event_TECNICO_2_BOTAOMouseClicked

    private void TECNICO_3_BOTAOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TECNICO_3_BOTAOMouseClicked
        // TODO add your handling code here:
        if(TECNICO_3_BOTAO.isSelected()){
            TECNICO_3_BOTAO.setSelected(true);
            TECNICO_3_BOTAO.setBackground(Color.red);
        }else{
            TECNICO_3_BOTAO.setSelected(false);
            TECNICO_3_BOTAO.setBackground(Color.green);
        }
    }//GEN-LAST:event_TECNICO_3_BOTAOMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAO_ZERAR;
    private javax.swing.JToggleButton TECNICO_1_BOTAO;
    private javax.swing.JToggleButton TECNICO_2_BOTAO;
    private javax.swing.JToggleButton TECNICO_3_BOTAO;
    private javax.swing.JLabel TEXTO_NOME_DA_VEZ;
    private javax.swing.JLabel TEXTO_TOTAL;
    // End of variables declaration//GEN-END:variables
}